### ISSUE TITLE
Dotaz na přesnost hodnocení.

### ISSUE THREAD

**Issue by PavelKriz** [3DprintFIT/B192HW-Assignment#1]
Ahoj,
rád bych se ujistil zda jsou tolerovány malé odchylky typu: Score 0.9967.

Všiml jsem si, že jisté rozdíly vznikají při vzorkování na nakloněných hranách( "zuby" jsou jinde na nakloněné hraně). Předpokládám také, že rozdíl v barvách také nehraje roli.

Příklad rozdílu barev:
(Student)
![student](https://user-images.githubusercontent.com/45934188/82809903-76448200-9e8d-11ea-8061-89dd6700d232.png)
(Reference)
![reference](https://user-images.githubusercontent.com/45934188/82809911-7cd2f980-9e8d-11ea-97a0-1c9296c2db4f.png)

Předem děkuji za pochopení a odpověď. Nerad bych nedostal body za něco co jsem ještě mohl opravit například.

**Comment by hroncok** [comment]
Rozdíl v hranách oblouků a v barvách nehraje při hodnocení roli. Číslo je pouze debug informace pro nás.

Konkrétně uvedený příklad považuji za 100% správné řešení.
